services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: YOUR_DB_HOST
      - key: DB_POSTGRESDB_DATABASE
        value: YOUR_DB_NAME
      - key: DB_POSTGRESDB_USER
        value: YOUR_DB_USER
      - key: DB_POSTGRESDB_PASSWORD
        value: YOUR_DB_PASS
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: https://your-n8n-app.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: YOUR_SECRET_KEY
databases:
  - name: n8n-db
    plan: free
